### ISSUE TITLE
node-sass dependency breaking on Windows build

### ISSUE THREAD

**Issue by rossmullen** [govau/design-system-components#955]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Running `npm i` within `packages/<any component>` on a Windows PC causes the build to fail at the node-sass dependency stage. The error log describes being unable to find Python which I suspect is installed on a Mac by default but not PC's.

## What I expected to happen

`npm i` to complete successfully when run within a `packages/<any component>` directory.

## Reproducing

- Module name: `@gov.au/callout`
- Module version: `3.0.2`
- Pancake version: `1.0.0`
- Node version: `14.15.4`
- npm version: `6.14.10`
- Pancake settings in your `package.json`:

Steps to reproduce:

1. `npm i`
2. `npm run boostrap`
3. `cd packages/callout`
4. `npm i`

## Attachments

```
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

> node-sass@4.9.3 install C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.9.3 postinstall C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\IEUser\\Desktop\\design-system-components\\design-system-components\\packages\\callout\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\Desktop\\design-system-components\\design-system-components\\packages\\callout\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\IEUser\Desktop\design-system-components\design-system-components\packages\callout\node_modules\node-sass
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN notsup Unsupported engine for @gov.au/core@3.4.2: wanted: {"node":">=0.12.0","npm":"^3.0.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm WARN notsup Not compatible with your version of node/npm: @gov.au/core@3.4.2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\browser-sync\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rossmullen** [comment]
Removal of `package-lock.json` file in the packages/callout folder overcomes the problem. Suspect `package-lock.json` has the earlier version of the node-sass dependency, and this is rebuilt when `npm i` is run causing the error.

**Comment by rossmullen** [comment]
No longer a problem. Whilst the error message is due to the `node-sass` version , the issue ultimately occurred due to unfamiliarly with the build process. Design-system-components is a monorepo running `npm i` within a packages directory will cause significant headaches.
